language: ruby
sudo: required
cache: bundler
dist: trusty

jdk:
  - oraclejdk8
rvm:
  - 2.3.4
before_script:
  - bundle exec rake db:create
script:
  - xvfb-run -a bundle exec rake travis
addons:
  apt:
    packages:
     - imagemagick
services:
  - redis-server
notifications:
  email: false
