language: ruby
sudo: false
cache:
  bundler: true
dist: trusty

jdk:
  - oraclejdk8
rvm:
  - 2.4.1
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - bundle exec rake db:create
  - bundle exec rubocop
script:
  - bundle exec rake ci
addons:
  apt:
    packages:
     - imagemagick
services:
  - redis-server
notifications:
  email: false
