language: ruby
sudo: required

cache:
  bundler: true
dist: trusty

jdk:
  - oraclejdk8
rvm:
  - 2.4.1
before_install:
  - gem update --system
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - wget -N http://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
before_script:
  - bundle exec rake db:create
  - bundle exec rubocop
script:
  - xvfb-run -a bundle exec rake ci
addons:
  chrome: stable
  apt:
    packages:
      - imagemagick
services:
  - redis-server
notifications:
  email: false
